In [1]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
arr1 = np.array( [4, 5, 6])
print(arr1)

[4 5 6]


In [8]:
arr + arr1 

array([5, 7, 9])

In [10]:
arr + 5

array([6, 7, 8])

In [11]:
print(arr)
arr2 = np.array([[2], [5], [7]])
print(arr2)

[1 2 3]
[[2]
 [5]
 [7]]


In [12]:
arr + arr2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [14]:
arr3 = np.array([1,2,3])
arr4 = np.array([1,2,3, 4, 5])

In [15]:
arr3 + arr4

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [17]:
arr5 = np.array([1,2,3])
arr6 = np.array([[1,2,3], [4,5,6]])
print(arr5.shape)
print(arr6.shape)
print(arr5.ndim, arr6.ndim)

(3,)
(2, 3)
1 2


Broadcasting is NumPy's way of doing arithmetic between arrays of different shapes — without manually resizing them.
Simple definition — NumPy automatically stretches the smaller array to match the shape of the larger one so the operation can work.