In [21]:
import numpy as np

Broadcasting is NumPy's way of doing arithmetic between arrays of different shapes — without manually resizing them.
Simple definition — NumPy automatically stretches the smaller array to match the shape of the larger one so the operation can work.

In [7]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
arr1 = np.array( [4, 5, 6])
print(arr1)

[4 5 6]


In [8]:
arr + arr1 

array([5, 7, 9])

In [10]:
arr + 5

array([6, 7, 8])

In [11]:
print(arr)
arr2 = np.array([[2], [5], [7]])
print(arr2)

[1 2 3]
[[2]
 [5]
 [7]]


In [12]:
arr + arr2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [14]:
arr3 = np.array([1,2,3])
arr4 = np.array([1,2,3, 4, 5])

In [15]:
arr3 + arr4

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [17]:
arr5 = np.array([1,2,3])
arr6 = np.array([[1,2,3], [4,5,6]])
print(arr5.shape)
print(arr6.shape)
print(arr5.ndim, arr6.ndim)

(3,)
(2, 3)
1 2


NumPy's random module generates random numbers for simulations, data science, deep learning weight initialization, testing and more.

In [1]:
from numpy.random import Generator as gen, PCG64 as pcg

In [11]:
arr_rg = gen(pcg(seed=101))
arr_rg.normal(size=(3, 4))

array([[-0.7901525 , -2.03462548,  0.60330175,  0.74429453],
       [-0.3096868 ,  0.36732137,  1.71039429,  1.06079784],
       [ 0.70763902,  0.68774939, -0.86356745,  0.96401673]])

In [16]:
arr_rg = gen(pcg(seed=200))
arr_rg.integers(low=0, high=100, size=(3, 4))

array([[ 3, 64, 23, 66],
       [33,  2, 54, 17],
       [89, 57, 43, 55]])

In [18]:
arr_rg = gen(pcg(seed=200))
arr_rg.random(size=(3, 4))

array([[0.64683414, 0.66391997, 0.02990165, 0.17783134],
       [0.57349665, 0.55116402, 0.52692044, 0.37424281],
       [0.0607941 , 0.36999257, 0.35751452, 0.24155704]])

NumPy Indexing:
NumPy arrays (ndarray) allow you to access and modify elements using indexing (like Python lists) but with more powerful features.

NumPy Index Slicing:
NumPy slicing allows you to extract subsets of arrays using the start:stop:step syntax. It is a powerful feature for manipulating data efficiently.


arr[row, col]   ← always use this for NumPy - single operation
arr[row][col]   ← works but avoid — Python list style - 2 operation



In [31]:
arr11 = np.array([[1, 2, 3], [4, 5, 6]])
arr11

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr11[0,1] 
# arr11[1]

2

In [29]:
arr11[0][1]

2

In [34]:
arr12 = [1, 2, 3, 4, 5]
print(arr12[-1])
print(arr11[-1])

5
[4 5 6]


In [36]:
arr11[1,2] = 66
print(arr11)
arr11[1] = 99
print(arr11)

[[ 1  2  3]
 [ 4  5 66]]
[[ 1  2  3]
 [99 99 99]]


In [41]:
arr12 = np.array([[1, 2, 3], [4, 5, 6]])
arr12[0, 1]  + 2
# arr12[0] + 5

4

Slicing in numpy arrays is similar to slicing in Python lists, but it can be applied to multi-dimensional arrays as well. Here are some examples of slicing in numpy arrays:

In [42]:
arr21 = np.array([[1, 2, 3], [4, 5, 6]])
arr21[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr21[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr21[0:1] #only first row

array([[1, 2, 3]])

In [48]:
arr21[0:1, 2:] #empty array, as there is no 4th column
arr21[0:1, 3:] #empty array, as there is no 4th column

array([], shape=(1, 0), dtype=int64)

In [50]:
arr_max = np.array([
    [1,  2,  3,  4,  5,  6],
    [7,  8,  9,  10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24]
])

In [52]:
arr_max[0:1]

array([[1, 2, 3, 4, 5, 6]])

In [55]:
arr_max[0:2, 1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

arr_max[0:2,1:4]
0:2
→ Row part
start=0 (included)
stop=2 (excluded)
= rows 0 and 1 only

1:4
→ Column part
start=1 (included)
stop=4 (excluded)

arr[0:2, 1:4]
      ↑     ↑
  stop-1  stop-1
    = 1    = 3   ← last index actually included

0 → included    1 → included
1 → included    2 → included
2 → EXCLUDED    3 → included
                4 → EXCLUDED

In [56]:
arr_max[2:3, 3:5]

array([[16, 17]])

In [58]:
arr_max[2:, 3:]

array([[16, 17, 18],
       [22, 23, 24]])

In [59]:
arr_max[0:3:2, 0:5:2]

array([[ 1,  3,  5],
       [13, 15, 17]])

arr_max[
0:3:2
,
0:5:2
]
0:3:2 → rows
start
0
 include row 0
stop
3
 stop before row 3
step
2
 jump by 2 rows
0:5:2 → columns
start
0
 include col 0
stop
5
 stop before col 5
step
2
 jump by 2 cols


arr_max[0:3:2,  0:5:2]
         ↑ ↑ ↑   ↑ ↑ ↑
         | | |   | | └── step = 2 (jump every 2 cols)
         | | |   | └──── stop = 5 (exclude col 5)
         | | |   └────── start = 0 (include col 0)
         | | └────────── step = 2 (jump every 2 rows)
         | └──────────── stop = 3 (exclude row 3)
         └────────────── start = 0 (include row 0)

Step tells you how many to jump — step 2 means pick one, skip one, pick one, skip one.