NumPy Array Shape Manipulation — reshape, ravel, and flattenNumPy arrays have a shape (a tuple describing dimensions) and size (total number of elements). Shape manipulation lets you reorganize the same data into different dimensional layouts without changing the underlying values.

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
reshaped = arr.reshape(3, 4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
flatten = reshaped.flatten()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
ravel = reshaped.ravel()
ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Different types of array

In [14]:
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
arr1.ndim

2

In [16]:
arr1.dtype

dtype('int64')

In [17]:
arr1.shape

(3, 5)

In [19]:
zeros = np.zeros((2, 3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
arr_r = np.arange(1, 10)
arr_r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_d = np.linspace(1, 5, 10)
arr_d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])